[supabase]
url = "https://iidfqtkbiuqjivmfnfyw.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlpZGZxdGtiaXVxaml2bWZuZnl3Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0MDg0MjczOCwiZXhwIjoyMDU2NDE4NzM4fQ.bAA-J1KB1Km4NNILcjDPczJLQsV-kAXLhzAktgrtc6k"